min_version = { soft = "2026.7.11" }

[tools]
node = "24"
pnpm = "11"

[env]
_.path = [
  "{{config_root}}/node_modules/.bin"
]  # https://mise.jdx.dev/mise-cookbook/nodejs.html#add-node-modules-binaries-to-the-path
